[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/apps"
  to = "/.netlify/functions/apps"
  status = 200

[[redirects]]
  from = "/api/app-image"
  to = "/.netlify/functions/app-image"
  status = 200
